---
all:
  children:
    ado:
      hosts:
        WSVPRDADO01:
          ansible_host: WSVPRDADO01.int.chickasaw.net
          ansible_user: ansible
        
    k8s_internal:
      hosts:
        WSVLSTGK8S01:
          ansible_host: WSVLSTGK8S01.int.chickasaw.net
          ansible_user: ansible
        WSVLSTGK8S02:
          ansible_host: WSVLSTGK8S02.int.chickasaw.net
          ansible_user: ansible
        WWSVLSTGK8S03:
          ansible_host: WSVLSTGK8S03.int.chickasaw.net
          ansible_user: ansible

    k8s_external:
      hosts:
        WSVLDMZSTGK8S01:
          ansible_host: WSVLDMZSTGK8S01.int.chickasaw.net
          ansible_user: ansible
        WSVLDMZSTGK8S02:
          ansible_host: WSVLDMZSTGK8S02.int.chickasaw.net
          ansible_user: ansible
        WSVLDMZSTGK8S03:
          ansible_host: WSVLDMZSTGK8S03.int.chickasaw.net
          ansible_user: ansible

    msdynamics:
      children:
        web:
          hosts:
            WINDMZVSTGDWB01:
              ansible_host: WINDMZVSTGDWB01.int.chickasaw.net
              ansible_user: Ansible_ECS
              ansible_winrm_transport: ntlm
              ansible_connection: winrm
              ansible_port: 5985

            WINDMZVSTGDWB02:
              ansible_host: WINDMZVSTGDWB02.int.chickasaw.net
              ansible_user: Ansible_ECS
              ansible_winrm_transport: ntlm
              ansible_connection: winrm
              ansible_port: 5985
        app:
          hosts:
            WINVSTGDYNAPP01:
              ansible_host: WINVSTGDYNAPP01.int.chickasaw.net
              ansible_user: Ansible_ECS
              ansible_winrm_transport: ntlm
              ansible_connection: winrm
              ansible_port: 5985

            WINVSTGDYNAPP02:
              ansible_host: WINVSTGDYNAPP02.int.chickasaw.net
              ansible_user: Ansible_ECS
              ansible_winrm_transport: ntlm
              ansible_connection: winrm
              ansible_port: 5985

            WINVSTGDYNAPP03:
              ansible_host: WINVSTGDYNAPP03.int.chickasaw.net
              ansible_user: Ansible_ECS
              ansible_winrm_transport: ntlm
              ansible_connection: winrm
              ansible_port: 5985
        sql:
          hosts:
            WINVSTGDYNDB01:
              ansible_host: WINVSTGDYNDB01.int.chickasaw.net
              ansible_user: Ansible_ECS
              ansible_winrm_transport: ntlm
              ansible_connection: winrm
              ansible_port: 5985

    mongodb:
      hosts:
        WSVSTGMDB01:
          ansible_host: WSVSTGMDB01.int.chickasaw.net
          ansible_user: ansible
        WSVSTGMDB02:
          ansible_host: WSVSTGMDB02.int.chickasaw.net
          ansible_user: ansible
        WSVSTGMDB03:
          ansible_host: WSVSTGMDB03.int.chickasaw.net
          ansible_user: ansible

k8s:
  children:
    k8s_internal:
    k8s_external:
         
