all:
  children:
    ado:
      hosts:
        ADAVPRDADO01:
          ansible_host: ADAVPRDADO01.int.chickasaw.net
          ansible_user: ansible

    registry:
      hosts:
        ADAVPRDREG01:
          ansible_host: ADAVPRDREG01.int.chickasaw.net
          ansible_user: ansible

    k8s_internal:
      hosts:
        ADAVLPRDK8S01:
          ansible_host: ADAVLPRDK8S01.int.chickasaw.net
          ansible_user: ansible
        ADAVLPRDK8S02:
          ansible_host: ADAVLPRDK8S02.int.chickasaw.net
          ansible_user: ansible
        ADAVLPRDK8S03:
          ansible_host: ADAVLPRDK8S03.int.chickasaw.net
          ansible_user: ansible

    k8s_external:
      hosts:
        ADAVDMZPRDK8S01:
          ansible_host: ADAVDMZPRDK8S01.int.chickasaw.net
          ansible_user: ansible
        ADAVDMZPRDK8S02:
          ansible_host: ADAVDMZPRDK8S02.int.chickasaw.net
          ansible_user: ansible
        ADAVDMZPRDK8S03:
          ansible_host: ADAVDMZPRDK8S03.int.chickasaw.net
          ansible_user: ansible
        
    mongodb:
      hosts:
        ADAVPRDMDB01:
          ansible_host: ADAVPRDMDB01.int.chickasaw.net
          ansible_user: ansible
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        ADAVPRDMDB02:
          ansible_host: ADAVPRDMDB02.int.chickasaw.net
          ansible_user: ansible
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        ADAVPRDMDB03:
          ansible_host: ADAVPRDMDB03.int.chickasaw.net
          ansible_user: ansible
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    msdynamics:
      children:
        web:
          hosts:
            ADADMZVPRDDWB01:
              ansible_host: ADADMZVPRDDWB01.int.chickasaw.net
              ansible_user: Ansible_ECS
              ansible_winrm_transport: ntlm
              ansible_connection: winrm
              ansible_port: 5985
            ADADMZVPRDDWB02:
              ansible_host: ADADMZVPRDDWB02.int.chickasaw.net
              ansible_user: Ansible_ECS
              ansible_winrm_transport: ntlm
              ansible_connection: winrm
              ansible_port: 5985

        app:
          hosts:
            ADAVPRDDYNAPP01: 
              ansible_host: ADAVPRDDYNAPP01.int.chickasaw.net
              ansible_user: Ansible_ECS
              ansible_winrm_transport: ntlm
              ansible_connection: winrm
              ansible_port: 5985
            ADAVPRDDYNAPP02: 
              ansible_host: ADAVPRDDYNAPP02.int.chickasaw.net
              ansible_user: Ansible_ECS
              ansible_winrm_transport: ntlm
              ansible_connection: winrm
              ansible_port: 5985
            ADAVPRDDYNAPP03: 
              ansible_host: ADAVPRDDYNAPP03.int.chickasaw.net
              ansible_user: Ansible_ECS
              ansible_winrm_transport: ntlm
              ansible_connection: winrm
              ansible_port: 5985

        sql:
          hosts:
            ADAVPRDDYNDB01:
              ansible_host: ADAVPRDDYNDB01.int.chickasaw.net
              ansible_user: Ansible_ECS
              ansible_winrm_transport: ntlm
              ansible_connection: winrm
              ansible_port: 5985
            ADAVPRDDYNDB02:
              ansible_host: ADAVPRDDYNDB02.int.chickasaw.net
              ansible_user: Ansible_ECS
              ansible_winrm_transport: ntlm
              ansible_connection: winrm
              ansible_port: 5985
            WINVPRDDYNDB02:
              ansible_host: WINVPRDDYNDB02.int.chickasaw.net
              ansible_user: Ansible_ECS
              ansible_winrm_transport: ntlm
              ansible_connection: winrm
              ansible_port: 5985

    k8s:
      children:
        k8s_internal:
        k8s_external:
         
