# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cn-ecs-identity-app.fullname" . }}-config
  labels:
    {{- include "cn-ecs-identity-app.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
