all:
  children:
    ado:
      hosts:
        ADAVDEVADO01:
          ansible_host: ADAVDEVADO01.int.chickasaw.net
          ansible_user: ansible
          
    artifactory:
      hosts:
        ADAVPRDREG01:
          ansible_host: ADAVPRDREG01.int.chickasaw.net
          ansible_user: ansible
    k8s:
      hosts:
        ADAVDEVK8S01:
          ansible_host: ADAVDEVK8S01.int.chickasaw.net
          ansible_user: ansible
        ADAVDEVK8S02:
          ansible_host: ADAVDEVK8S02.int.chickasaw.net
          ansible_user: ansible

    msdynamics:
      children:
        web:
          hosts:
            ADAVDEVCRMWEB01:
              ansible_host: ADAVDEVCRMWEB01.int.chickasaw.net
              ansible_user: ansible
        app:
          hosts:
            ADAVDEVCRMAPP01:
              ansible_host: ADAVDEVCRMAPP01.int.chickasaw.net
              ansible_user: ansible
        sql:
          hosts:
            ADAVDEVCRMDB01:
              ansible_hosts:
              ansible_user:
    mongodb:
      hosts:
        ADAVDEVMDB01:
          ansible_host: ADAVDEVMDB01.int.chickasaw.net
          ansible_user: ansible

