replicaCount: 1
image:
  repository: cn-ecs-chokwaa-app
  tag: "1.0.68"
ingress:
  enabled: true
  host: test-my-chickasaw.int.chickasaw.net
env:
  VITE_WEBAPP_BASE_URL: "https://test-ecs-chokwaaapi.int.chickasaw.net"
  VITE_CHOKWAA_AUTHORITY: "https://test-ecs-myaccount.int.chickasaw.net/"
  VITE_CHOKWAA_CLIENT_ID: "chokwaa-app-test"
createSecret: false
secrets: {}
