formio:
  replicaCount: 1

  image:
    repository: formio/formio-enterprise
    tag: "8.3.3"
    pullPolicy: IfNotPresent
  port: 3001

pdf:
  replicaCount: 1
  image:
    repository: formio/pdf-server
    tag: "5.0.0"
    pullPolicy: IfNotPresent
  port: 4005

env:
  PORTAL_ENABLED: false
  LICENSE_KEY: #{licenseKey}
  SSO_TEAMS: false
  ADMIN_EMAIL: admin@company.com
  PDF_SERVER: https://dev-myforms.chickasaw.net/pdf
  FORMIO_PDF_PORT: ""
  FORMIO_S3_SERVER: "https://dev-myfiles.chickasaw.net"
  FORMIO_S3_BUCKET: formio-file-upload-test
  FORMIO_S3_PORT: 443
  FORMIO_S3_BUCKET: "formio-file-upload-test"
  FORMIO_S3_KEY: "formio-file-upload-test-user"
  PORT: "8081"
   
ingress:
  enabled: true
  host: test-ecs-formio.int.chickasaw.net