apiVersion: v1
kind: Secret
metadata:
  name: azure-devops-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
stringData:
  type: git
  url: "ssh://azdevops.int.chickasaw.net:22/Tribal%20Services/Enhanced%20Citizen%20Services/_git"
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAgEAv21Rj3w+yKc0HhFBqjSkfKLAhqMNAO1NUPrOKkfjTmTT0q2R2IaF
    HNWw9imrKSp4GzbhF5vjIEg5rNbAltdy8xO4Fd9TctDoSNx1VynmeCKC+A/s1P61kQm379
    6jvPnXr67bEjosYpHvRwzcZnOqBRrkNdmDMpvuTXnNm732ShE5ZsO2zcKEqOHKT51TtVew
    STKvbJ7sWdmiHYFK6eBheSdKv0a96YjCOBAr3ZUJOo+DOcRmT1aRmawnZifs2pN9NH4WkF
    PNMlBvRWaRMPPKGWKt5NxkreBZ/y+H/1yxS6KXk4FuXueEl21t915MTRMNcMEsJRIvHvz2
    BmRqSDO9S/ok5thgBYYC+/3AQ0zh2P6KIDodVP9KSPCdisJbdMCI+RoXTu0zBZwTInSRAl
    lc3DG1yMj5g1YSUwFJfXO5KErwkrRmdia3wja/4K3vswBs1IGomkgfOCDAzXM7fgP3+kEj
    zgjbCJlxLdJGlGG4MKFT5JPyz6Gi2BHXyNY3SGFDmdYdQwxY85jv9Vy7mOOm2bXuZui9cW
    h3Mj6VL0uHUUs09mWnIr2MXHZ/nkZjnULiafxj4oaHc9nSh6GPPqDDaIw+Al1d21UfikLU
    PXXnvLQ0/r3mQ9hJ/FFohl3C91feZ/ThPamVVR8AAeXhNvaefYtWJmWErJS+WEGgj0Y2Hy
    sAAAdIanqU0Wp6lNEAAAAHc3NoLXJzYQAAAgEAv21Rj3w+yKc0HhFBqjSkfKLAhqMNAO1N
    UPrOKkfjTmTT0q2R2IaFHNWw9imrKSp4GzbhF5vjIEg5rNbAltdy8xO4Fd9TctDoSNx1Vy
    nmeCKC+A/s1P61kQm3796jvPnXr67bEjosYpHvRwzcZnOqBRrkNdmDMpvuTXnNm732ShE5
    ZsO2zcKEqOHKT51TtVewSTKvbJ7sWdmiHYFK6eBheSdKv0a96YjCOBAr3ZUJOo+DOcRmT1
    aRmawnZifs2pN9NH4WkFPNMlBvRWaRMPPKGWKt5NxkreBZ/y+H/1yxS6KXk4FuXueEl21t
    915MTRMNcMEsJRIvHvz2BmRqSDO9S/ok5thgBYYC+/3AQ0zh2P6KIDodVP9KSPCdisJbdM
    CI+RoXTu0zBZwTInSRAllc3DG1yMj5g1YSUwFJfXO5KErwkrRmdia3wja/4K3vswBs1IGo
    mkgfOCDAzXM7fgP3+kEjzgjbCJlxLdJGlGG4MKFT5JPyz6Gi2BHXyNY3SGFDmdYdQwxY85
    jv9Vy7mOOm2bXuZui9cWh3Mj6VL0uHUUs09mWnIr2MXHZ/nkZjnULiafxj4oaHc9nSh6GP
    PqDDaIw+Al1d21UfikLUPXXnvLQ0/r3mQ9hJ/FFohl3C91feZ/ThPamVVR8AAeXhNvaefY
    tWJmWErJS+WEGgj0Y2HysAAAADAQABAAACACo9l7FHU91YFAaMfUZvLlq4WS58fUqWkqiL
    Z4Hp8g0i76D+HwA+EtJ9jvqK0FOZpP4wWnQouHIvrdZnXwEKErnzwHvHF3VvBsrJJvVwcA
    RTbT4K2ZJYkD0sfVOnd88j/IWuWnYHszKfDENL4biTzlEpEXGWiT5aLTgYaBf1T4shiN6V
    0llOEpLnnAp8Z3PNIT/NuOsJmJLtFLpZBOxd0HR5CKPzmsWVIXJYky1mjS5Ia8cMAR2Bt0
    hHNjxzE+9Ze1fheN4pN87h8+PHEcPRD+gRH9kwDuFVb9aBKQve6tqLStJITdAQW3BEu+7J
    dqHNUfpvDewyOoamgC2B6/f5vsvKy6krZDFnqbKd9OdRbqEv8ChmB7APKtavtkk97VvJf2
    cn1qE07kptCYarw9aDU3GJbul0d023z3qHBkXXfyr5h7E9SwjHkqPBe/1TVNxGxwgxmw0s
    KEMUC2bnPOTzqEBEhc8Z5Lbr6Q/+a6LYxIspni74cfg6H13gHbEHTvd5itWjlGf0msDwiL
    FScnIqu8rGMtTj64EAYTtRVgz7niLR64QYl+m5WcY3+wKrHSoLeByRYijb7kpvJNEedo09
    Aeu9eiwb2FTrhCEGPSqqxVnV/Z3Q2q0V+lEmBLyVK6EY+e/muJG8+CZlLzmyZ25qQzXSgy
    PUDqFa0eDhGvegygv9AAABAEsjoT2IZbr6X/RgkEgSKf0NadLNQE76PLURzVaToghG/gBv
    wirFTOQ4FkMDhgQ27RpURdhzSbvhutMJg1YU6nIB4o6jJSocvSQT6iWX1kQevbOFeLGst6
    zF38H917BA46XGPa1/EH6+OUtZfjJU6Gav6hJh/6AbtSI9BXECpJNFUo8mBBaz8PHx9380
    p9R4Lx9/GXMzUlUJMuqg2X7kPwAJhS1pIuP6SPvsBi+dGSNMBgk3+lkgxNZmVjMlBEmV0y
    MbsK8LudX+CKE6vdibj9AdY7Tm3uKdSpAkqkxZIMioYwozXcQ4z/cxPexrwHhLQOGp3XL9
    AT9mQW/eV/fjPO4AAAEBAOsSEaYg0voXNlVDDlF/hNtqOaJZR/5XKfGJGOysN9OiDjxwy8
    FQ5ryLJecca8J6yGZIWJw5lNAe6FJf39Inl867kIJT2d67SbuXJTA00arCBhG29U1SNaJN
    EhT2BPnkUThjenr0wW9PPaKKpfVYBzZO1fjiHwV1hWPZTAGTOlBNVJURRnNj4gnfXgTdUu
    Rw/MWS056anraDKUatHfmnHeGKdu//iIlmsuWGQCKVoytqa8/sAD1+8PdMDWGxUezvoPZV
    G/WX37fxuGr4wh+2OxbvY8aQlYASV0WbQSOI5yasn0FFoR03grjy0SP33gnSA6SagE6M5m
    rXWQZo34kLVb0AAAEBANB4fPe8GUd9zR3syapacvbfNgcsRVEf6QD9/8ab/e9MG/ViThur
    CvYVqYYyhxRSTXz7MLk4hAQenyuOnr3ZAITMa1sKHvl19rRJ3Ykb9P/S64dDH2U39kzyw3
    22yjh6vctC7AdE1mG+hkZPmSCKnOLv3/VNl1atOKGXsEOo/SSPyhe87ZzG+u4tHuv1vFLs
    ufNiBrZQ3iaG3Lq9LbGEvl+z3K+n3L3TaHHAk5bha4HUWC41Ox8+ns+rBN7I/0DXCE55ZH
    rdwI/tk+oa23OmRJkGMxcefJlIjpE3YB5i6kWxZrDR/kpJR+iaWYX1+OMj1bx6hDaO4aNq
    Ly2N3Yns0wcAAAATYXJnb2NkLWF6dXJlLWRldm9wcw==
    -----END OPENSSH PRIVATE KEY-----
