apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dynatrace
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://azdevops.int.chickasaw.net:22/Tribal%20Services/Enhanced%20Citizen%20Services/_git/cn_ecs_helm_charts
    targetRevision: refs/heads/main
    path: helm_charts/dynatrace
    helm:
      releaseName: dynatrace
      valueFiles:
        - stage-ext-values.yaml
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dynatrace
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true