{{- if .Values.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cn-ecs-web-app.fullname" . }}-secrets
type: Opaque
stringData:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
